version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
       - '5432:5432'
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    network_mode: host
    environment:
      PYTHONUNBUFFERED: 1 
    depends_on:
      - db

volumes:
  postgres_data:
