version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    network_mode: host
    environment:
      PYTHONUNBUFFERED: 1 
    depends_on:
      - db

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    ports:
      - "1883:1883"  # Puerto para MQTT (sin TLS)
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - mosquitto_conf:/mosquitto/config
    environment:
      - MQTT_USERNAME=myuser
      - MQTT_PASSWORD=mypassword
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  mosquitto_conf:
